name: Deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: larademo
          mysql user: root
          mysql password: root
      # Geneate .env with Github secrets
      - name: Generate .env
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=localhost" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=larademo" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install node dependencies
        run: npm ci
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache
      - name: Run Unit tests
        env:
          APP_ENV: testing
          DB_CONNECTION: localhost
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DATABASE: larademo
        run: php artisan test
      - name: Archive Built Project artifacts
        run: tar -czf project.tar.gz .

      - name: Transfer Archive to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "project.tar.gz"
          target: ${{ secrets.SSH_PROJECT_PATH }}
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.SSH_PROJECT_PATH }}
            tar -xzf project.tar.gz
            rm project.tar.gz
            # Update file permissions if necessary
            chmod 755 -R storage bootstrap/cache
            # Update .env file


      # - name: Deploy to Server
      #   if: ${{ success() }}
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script_stop: true
      #     script: |
      #       cd /home4/melivje1/cdx.melivo.us
      #       git pull
      #       npm ci
      #       npm run prod
      #       composer i
      #       php artisan migrate --force
